Repository Lembas-Modding-Team/lotr-mod-translations, pull requests merged in 2020-05, with the labels that each got.

#3 Generalise formatting
  .gitattributes
  Renewed/en_us.json
  Renewed/fr_fr.json
  Renewed/it_it.json
  Renewed/ko_kr.json
  Renewed/zh_cn.json
Labels: fix

#4 Update nl_nl.json
  Renewed/nl_nl.json
Labels: duplicate, fix

#12 Pirate Update 1.2
  Renewed/en_pt.json
Labels: addition, existing language

#11 Update Dutch translations for Renewed 1.2
  Renewed/nl_nl.json
Labels: addition, existing language
